### PR TITLE
Add support for Opt and ForcePaymentMethod parameters for PxPay (2.x)

### PR DESCRIPTION
**Pull request by leith**
Defined on page 12 of the PxPay Integration guide

### CODE REVIEW

**Comment by leith** [comment]
@barryvdh, who's the best person to review this?

**Comment by leith** [comment]
@barryvdh with #56 now merged into master, are we able to get this one merged into the 2.x branch as well?

**Comment by webwaldo** [comment]
Yeah, really keen to see this make it into the 2.x branch too.

**Comment by leith** [comment]
@barryvdh thanks for merging this in! Would we be able to get a patch increment tag as well so this is available as a stable version via Composer?

**Comment by webwaldo** [comment]
Yeah, 100% on this, I was just trying to find out what the process was to get this as a new release in composer too.

**Comment by barryvdh** [comment]
I released a new 3.x and 3.x release.

**Pull request merged**
