### PR TITLE
Check request body for result if it's not found in the query string

### PR DESCRIPTION
**Pull request by leith**

### CODE REVIEW

**Comment by barryvdh** [comment]
Can you provide a link to the docs, that this is valid?
And a test-case for this also?

**Comment by leith** [comment]
While there seems to be an increasing trend in gateways towards using POST instead of GET for returned results, in this case it isn't that this is something documented as returned from Payment Express - it's the assumption that you're going to be doing the processing directly in the page called with the result using the query string.

By adding a check to the POST request body, you can use other pages for the CompleteAuthorizeRequest by passing along the result back from Payment Express. This is important if you have a lot of other information you also need to send to your processing page which could potentially exceed URL character limits.

I've added a unit test for the POST version, although it's a trivial simulation (as if the POST is coming from Payment Express, rather than being parsed from elsewhere).

**Comment by delatbabel** [comment]
OK so we have tests now, any objections to merging?

**Comment by leith** [comment]
@delatbabel any update here? Shall I just remove the fork?

**Pull request merged**
