### PR TITLE
Add conditionals for optional fields to PxPay request

### PR DESCRIPTION
**Pull request by gdhnz**
MerchantReference, TxnId, TxnData1, TxnData2, and TxnData3 are all optional fields so instead of sending empty strings if they're not set, don't include them in the request at all.

### CODE REVIEW

**Comment by gdhnz** [comment]
When I branched, it already included my PxPost changes.  Once the PxPost changes have been merged, I'll resubmit the PxPay changes.

**Comment by kayladnls** [comment]
@gdhnz thanks for this! Can you add some tests to cover it, please?

**Comment by gdhnz** [comment]
Is updating testCompletePurchaseWithTransactionDataSuccess in PxPayCompletePurchaseSuccess.php with additional response tests for TxnData1, TxnData2, and TxnData3 enough?

**Comment by delatbabel** [comment]
Merged. Can someone please confirm that this works in production and then I will tag for release?

**Comment by gdhnz** [comment]
I've confirmed this works in production.

**Pull request merged**
