### PR TITLE
Add support for Payment Express PxFusion

### PR DESCRIPTION
**Pull request by steveh**
https://www.paymentexpress.com/Technical_Resources/Ecommerce_NonHosted/PxFusion

Very similar to eWay RAPID 3.0 - generate a form on your site which POSTs to Payment Express.

There is also an authorize/capture mechanism, but that requires access to a different API I don't have access to.

### CODE REVIEW

**Comment by HipsterJazzbo** [comment]
Would like someone to try this out before merging, as I can't test it myself. I don't have any access to PxFusion.

**Comment by delatbabel** [comment]
@eileenmcnaughton another one to look at if you have access to PXFusion?  This one should be reasonably safe because it just adds an extra gateway.

**Comment by eileenmcnaughton** [comment]
OK, I've requested some credentials for pxFuzion - will see if they reply

**Comment by kayladnls** [comment]
@eileenmcnaughton any word back from them? I can request some as well, but I don't know that that would help.

**Comment by eileenmcnaughton** [comment]
I do have credentials. I haven't had a chance to test - but I can definitely share the credentials with you

**Comment by eileenmcnaughton** [comment]
I had a little bit of a go at this & hit a few things

1) The standardised field in Omnipay for a merchant reference is transactionId rather than txnRef ie 
$tranDetail->txnRef = $this->getTransactionId();
& change the field that is validated. This is mentioned on the readme https://github.com/thephpleague/omnipay 

> All gateways will accept a subset of these options:
> 
>     card
>     token
>     amount
>     currency
>     description
>     transactionId
>     clientIp
>     returnUrl
>     cancelUrl

& further down ..

> $response->getTransactionReference(); // a reference generated by the payment gateway
> $response->getTransactionId(); // the reference set by the originating website if available.

2) with the same changes as pxPay pxFusion can support rebilling (https://github.com/thephpleague/omnipay-paymentexpress/pull/22/files )

3) the response method should have a function like 

```
    public function isTransparentRedirect() {
        return true;
    }

I haven't actually gotten to the point of a successful response yet but I think the Response class needs a getTransactionId() function - although I kinda thought that might be inherited

Call to undefined method Omnipay\PaymentExpress\Message\PxFusionCompletePurchaseResponse::getTransactionId()
```

**Comment by eileenmcnaughton** [comment]
Hmm - it seems that there might not be a field for the unique reference - other than merchantRefernce - which 'might' show up in the console and possibly for customers, like it does in pxPay.

If that is the case we might need to co-opt one of the UserTxnData1 fields for the transactionId to be retrievable from the CompletePurchase request. Otherwise matching up the response becomes hard.

**Comment by eileenmcnaughton** [comment]
In the case of the above, I would say that userTxnData1 =  $this->getTransactionId();

if there is no reason (of which I know none) for it to differ from the other field then we could still go with $tranDetail->txnRef = $this->getTransactionId();

The calling code only wants to be setting meaningful variables in a standardised way. It doesn't want to know about inner workings

**Comment by eileenmcnaughton** [comment]
At the other end (CompletePurchase) we want to be able to use

getTransactionId for our unique id
& 
getTransactionRef for the dps id

&
getCardReference for the token (we need to have set EnableAddBillCard first - which would potentially go in a createCardRequest class).

The data would come from

(arguably ) txnData1 

dpsTxnRef
dpsBillingId

**Comment by eileenmcnaughton** [comment]
NB I have now managed to get a successful trxn!

**Comment by eileenmcnaughton** [comment]
Hmm - I think the transactionId has to go in the merchantReference field. I have a feeling that is 'less pretty' but I can't find any other field that will reliable accept & return it.

**Comment by eileenmcnaughton** [comment]
This is my commit reflecting the above

https://github.com/thephpleague/omnipay-paymentexpress/commit/590684288baaf2d6838eafe9b493e8c44ff29074

With this commit I am able to integrate pxfusion into my application interchangeably with other gateways

**Comment by judgej** [comment]
`getTransactionReference()` - it is spelled out in full :-)

**Comment by delatbabel** [comment]
@eileenmcnaughton -- OK given the above, is this now OK to merge?  As per what @judgej said, getTransactionReference() should return the gateway's reference (even if the gateway refers to that as a transaction ID).

**Comment by eileenmcnaughton** [comment]
I added this PR which includes the changes I had to make to get it to complete... https://github.com/thephpleague/omnipay-paymentexpress/pull/33

**Comment by delatbabel** [comment]
OK so do I merge this one only, or just #33 or both or neither?  They seem to overlap a bit.

**Comment by eileenmcnaughton** [comment]
I incorporated this with some changes into #33 - looks like I need to fix a test though

**Comment by delatbabel** [comment]
OK so I should close this and merge #33 once the tests on #33 are passing, correct?

**Comment by eileenmcnaughton** [comment]
yeah I think so - I'll get back on it

**Comment by lukeholder** [comment]
What is the status of this PR @eileenmcnaughton ? or @delatbabel ?

**Comment by eileenmcnaughton** [comment]
I think this can be closed in favour of #33 - I did try to re-test just now but my test credentials seem to have been cancelled so I have emailed PaymentExpress

**Pull request closed without merging**
