### PR TITLE
Allow users to pick between PxPay1 or PxPay2

### PR DESCRIPTION
**Pull request by b3njamin**

### CODE REVIEW

**Comment by mediabeastnz** [comment]
+1, DPs recommends PxPay 2.0 so it seems silly not to have it in there.

**Comment by kayladnls** [comment]
What are the different features/functionality in version 1? I'll need to go through more documentation to make sure that the existing features will still work regardless of the version.

**Comment by b3njamin** [comment]
Surprisingly the APIs are exactly the same, we work with it quite extensively at work v1 & v2 as far as I can tell just use different web interfaces.

**Comment by mediabeastnz** [comment]
I haven't found any differences, i just know that DPS will set up all new accounts as PX Pay 2.0.
Is this also a Omnipay issue? e.g. not having an API to change endpoints?

**Comment by Glutnix** [comment]
+1, this would be nice

**Comment by mediabeastnz** [comment]
FYI PXPay 2.0 is the default endpoint now so any new accounts will not work with this module, without modification.

**Comment by delatbabel** [comment]
I think that this will need manual merging as it has been superseded by another PR. The PXPay 2.0 endpoint is now the default but that means that this module can no longer work for PXPay 1.0 users. @eileenmcnaughton -- any suggestions?

**Comment by eileenmcnaughton** [comment]
We might get away with ignoring this - v2 is really the thing now...All new accounts get v2 & if you don't have it you just need to contact them & they change it

**Comment by delatbabel** [comment]
OK -- should we add something to the package README to that effect? I will close this if no longer required.

**Comment by eileenmcnaughton** [comment]
You could add a note saying the v2 api is supported & link to this ticket if people want to read more about v1

**Comment by delatbabel** [comment]
Done.

**Comment by mediabeastnz** [comment]
With is comes another issue - https://github.com/thephpleague/omnipay-paymentexpress/issues/23

**Pull request closed without merging**
