### PR TITLE
Allow token billing

### PR DESCRIPTION
**Pull request by b3njamin**
- Allow token billing in all requests
- Dont force currency to NZD for CreateCard
- Allow creating cards as purchase TxnTypes

### CODE REVIEW

**Comment by mediabeastnz** [comment]
Yes please! was trying to work out why all my createCards were being sent as Auth types....

**Comment by kayladnls** [comment]
@b3njamin can you add some tests to cover this, then I'll gladly merge.

**Comment by eileenmcnaughton** [comment]
In a recent effort to get token rebilling going I found that in order to do it with no further intervention it is necessary to switch to pxPost (config you need to request). I got this going with your patches + https://github.com/thephpleague/omnipay-paymentexpress/pull/22

Note that I pulled your last 2 patches into a separate PR : https://github.com/thephpleague/omnipay-paymentexpress/pull/21

Thanks for giving me the start on this!

**Comment by delatbabel** [comment]
So does this need to be merged, or abandoned in favour of #21 and #22 which replace it?  Note that #22 is currently failing but I'll comment there separately.

**Comment by eileenmcnaughton** [comment]
If you merge this then I can rebase the others

**Comment by delatbabel** [comment]
OK merged. Go ahead and rebase, and pls fix the errors on #22.

**Pull request merged**
